name: Build & Push Images

on:
  push:
    branches:
      - master

jobs:
  push:

    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
         - php-version: 7.1
           alpine-version: 3.7
         - php-version: 7.2
           alpine-version: 3.9
         - php-version: 7.3
           alpine-version: 3.11

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: |
          PROD_IMAGE=${{ github.actor }}/php:${{ matrix.php-version }}
          DEV_IMAGE=${{ github.actor }}/php:${{ matrix.php-version }}-dev

          docker build --tag $PROD_IMAGE --build-arg ALPINE_VERSION=${{ matrix.alpine-version }} prod
          docker build --tag $DEV_IMAGE --build-arg BASE_IMAGE=$PROD_IMAGE dev

          echo "PROD_IMAGE=$PROD_IMAGE" >> $GITHUB_ENV
          echo "DEV_IMAGE=$DEV_IMAGE" >> $GITHUB_ENV

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          docker push $PROD_IMAGE
          docker push $DEV_IMAGE
