name: Build & Push Images

on:
  push:
    branches:
      - master

    tags:
      - v*

jobs:
  push:

    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
          # See https://liduan.net/2019/09/17/php-version-in-alpine-linux.html for PHP version vs Alpine version
         - php-version: 7.1
           alpine-version: 3.7
         - php-version: 7.2
           alpine-version: 3.9
         - php-version: 7.3
           alpine-version: 3.11

    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u oaklees --password-stdin

      - name: Publish images
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "-${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          [ "$VERSION" == "-master" ] && VERSION=""

          PROD_IMAGE=oaklees/php:${{ matrix.php-version }}-$VERSION
          PROD_IMAGE_VERSIONED=$PROD_IMAGE$VERSION

          DEV_IMAGE=oaklees/php:${{ matrix.php-version }}-dev
          DEV_IMAGE_VERSIONED=$DEV_IMAGE$VERSION

          docker build --tag $PROD_IMAGE --tag $PROD_IMAGE_VERSIONED --build-arg ALPINE_VERSION=${{ matrix.alpine-version }} prod
          docker build --tag $DEV_IMAGE --tag $DEV_IMAGE_VERSIONED --build-arg BASE_IMAGE=$PROD_IMAGE dev

          docker push $PROD_IMAGE
          docker push $PROD_IMAGE_VERSIONED
          docker push $DEV_IMAGE
          docker push $DEV_IMAGE_VERSIONED
