name: Build & Push Images

on:
  push:
    branches:
      - master

jobs:
  push:

    env:
      CONTAINER_REGISTRY: docker.io/oaklees

    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
          # See https://liduan.net/2019/09/17/php-version-in-alpine-linux.html for PHP version vs Alpine version
         - php-version: 7.1
           alpine-version: 3.7
         - php-version: 7.2
           alpine-version: 3.9
         - php-version: 7.3
           alpine-version: 3.11

    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login $CONTAINER_REGISTRY -u oaklees --password-stdin

      - name: Publish images
        run: |
          PROD_IMAGE=$CONTAINER_REGISTRY/php:${{ matrix.php-version }}
          DEV_IMAGE=$CONTAINER_REGISTRY/php:${{ matrix.php-version }}-dev

          docker build --tag $PROD_IMAGE --build-arg ALPINE_VERSION=${{ matrix.alpine-version }} prod
          docker build --tag $DEV_IMAGE --build-arg BASE_IMAGE=$PROD_IMAGE dev

          docker push $PROD_IMAGE
          docker push $DEV_IMAGE
